'use client';
import dynamic from 'next/dynamic';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, Plus, Minus, Pause, Play, X, Menu, Copy, Check, ZoomIn, ZoomOut, Workflow, ScanLine, Layers3 } from 'lucide-react';
const Scene = dynamic(() => import('./Scene'), { ssr: false });
const base = process.env.NEXT_PUBLIC_BASE_PATH || '/ian-gutierrez-portfolio';
const asset = (s: string) => `${base}/${s}`;
const email = 'ianvan.gutierrez@gmail.com';
const linkedIn = 'https://www.linkedin.com/in/ian-gutierrez-bba2131ab/';
const projects = [
  {slug:'vendor-map',name:'A clearer view of every vendor.',short:'Vendor map',org:'RG26 Technologies',type:'Zoho Creator / CRM / Leaflet',description:'Turning CRM records into an interactive map. Find vendors by location, explore an area, and get the details that matter.',image:'projects/vendor-map.jpg',label:'LOCATION INTELLIGENCE',zoho:true},
  {slug:'lead-marketplace',name:'From lost lead to new possibility.',short:'Lead marketplace',org:'RG26 Technologies',type:'Zoho CRM / Flow / Creator',description:'A connected journey from eligible leads to priced listings and purchased-detail delivery.',image:'projects/lead-marketplace.png',label:'CONNECTED COMMERCE',zoho:true},
  {slug:'crm-automation',name:'Signed. Synced. Moving forward.',short:'Contract-to-CRM automation',org:'BritePH',type:'Zoho CRM / Deluge',description:'Connecting signed-document conditions with CRM deal updates through custom Deluge logic.',image:'projects/evidence-29.png',label:'WORKFLOW AUTOMATION',zoho:true},
  {slug:'partner-lookup',short:'Partner company lookup',type:'Zoho Creator / Sheet / Deluge',zoho:true},
  {slug:'sunrise-clock',short:'Sunrise clock widget',type:'Zoho Creator / JavaScript',zoho:true},
  {slug:'ai-resume-analyzer',short:'AI Resume Analyzer',type:'Zoho Creator / Recruit / OpenAI · Proposed application',zoho:true},
  {slug:'event-reporting',short:'Event reporting & team updates',type:'Zoho Creator / Flow / Cliq',zoho:true},
  {slug:'zoho-analytics',short:'Zoho Analytics reporting',type:'Zoho Analytics / Data visualization',zoho:true},
  {slug:'google-chat-reminders',short:'Google Chat reminder app',type:'Apps Script / Google Chat / Sheets',zoho:false},
  {slug:'call-quality',short:'Call quality evaluation',type:'Application workflow',zoho:false},
  {slug:'nomo-pos',short:'Nomo POS interface design',type:'Product design',zoho:false},
  {slug:'applicant-readiness',short:'Applicant readiness report',type:'Reporting workflow',zoho:false},
  {slug:'ringcentral-workflows',short:'RingCentral call workflows',type:'Contact center configuration',zoho:false},
  {slug:'blog-design',short:'BritePH blog design',type:'Web & content design',zoho:false},
];
const awards = [
 ['Digital Luminary','digital-luminary.jpg'],['Deluge Prodigy','deluge-prodigy.jpg'],['Codeless Crusader','codeless-crusader.jpg'],['Creator Extraordinaire','creator-extraordinaire.jpg']
];
const credentials = [
 {title:'EF SET English Certificate',meta:'EF SET · 2 October 2025',detail:'77/100 · C2 Proficient',img:'ef-set-english.png',logo:'ef-set.jpg'},
 {title:'On-the-Job Training Certificate',meta:'MSU–IIT · 17 June 2022',detail:'Office of Institutional Planning and Development Services',img:'ojt-completion-updated.png',logo:'msu-iit.jpg'},
 {title:'Getting Started with ReactJS Components',meta:'Simplilearn SkillUP · 24 October 2022',detail:'Course completion',img:'reactjs-components-clean.png',logo:'skillup.png'},
 {title:'Introduction to Cyber Security',meta:'Simplilearn SkillUP · 22 October 2022',detail:'Course completion',img:'intro-cyber-security.jpg',logo:'csx-cybersecurity.png'},
];
type Preview = {src:string;title:string;meta:string};
function Mark({children}:{children:React.ReactNode;number:string}){return <div className="section-marker" aria-hidden="true"/>}
export default function Portfolio(){
 const [menu,setMenu]=useState(false),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(true),[failed,setFailed]=useState(false),[inView,setInView]=useState(true),[hidden,setHidden]=useState(false);
 const [filter,setFilter]=useState('all'),[preview,setPreview]=useState<Preview|null>(null),[copied,setCopied]=useState(false),[zoom,setZoom]=useState(false),[copyError,setCopyError]=useState(false);
 const dialog = useRef<HTMLDialogElement>(null), stage=useRef<HTMLDivElement>(null), trigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(media.matches);sync();media.addEventListener('change',sync);const visibility=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',visibility);return()=>{media.removeEventListener('change',sync);document.removeEventListener('visibilitychange',visibility)}},[]);
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setInView(entry.isIntersecting),{rootMargin:'100px'});if(stage.current)observer.observe(stage.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');obs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);
 useEffect(()=>{if(preview){dialog.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}}else {dialog.current?.close();trigger.current?.focus();setZoom(false)}},[preview]);
 const open=(p:Preview,e:React.MouseEvent<HTMLElement>)=>{trigger.current=e.currentTarget;setZoom(false);setPreview(p)};
 const copy=async()=>{setCopyError(false);try{await navigator.clipboard.writeText(email);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setCopied(false);setCopyError(true)}};
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="navigation" onKeyDown={e=>{if(e.key==='Escape'){setMenu(false);document.getElementById('menu-toggle')?.focus()}}}><a className="brand" href="#top" aria-label="Ian Gutierrez home">ian<span>.</span></a><button className="menu-toggle" id="menu-toggle" aria-controls="main-nav" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav id="main-nav" className={menu?'nav-links is-open':'nav-links'} aria-label="Main navigation"><a href="#work" onClick={()=>setMenu(false)}>Work</a><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#recognition" onClick={()=>setMenu(false)}>Credentials</a><a className="nav-cta" href="#contact" onClick={()=>setMenu(false)}>Let’s talk <ArrowUpRight size={17}/></a></nav></header>
 <main id="main">
 <section className="hero wrap" id="top">
 <div className="hero-topline"><span><i className="status-dot"/> IAN VAN ANTHONY GUTIERREZ</span><span>SOLUTIONS DEVELOPER & PROJECT MANAGER</span></div>
 <div className="hero-grid"><div className="hero-copy"><h1>Complexity,<br/>meet <span>clarity.</span></h1><p className="hero-intro">I build Zoho applications, automate workflows, and connect the systems your team depends on.</p><div className="hero-buttons"><a className="button dark" href="#work">Explore my work <ArrowDown size={18}/></a><a className="under-link" href="#contact">Let’s build something <ArrowUpRight size={18}/></a></div><div className="hero-person"><img src={asset('ian-hero-illustration.jpg')} alt="Illustrated avatar of Ian" width="48" height="48"/><span>Human-centered thinking.<br/><strong>End-to-end execution.</strong></span><span className="person-line"/></div></div>
 <div className="engine" ref={stage}><div className="engine-grid" aria-hidden="true"/><div className="engine-fallback" aria-hidden="true"><span/><span/><span/><i/></div>{!failed&&<div className="canvas-wrap"><Scene paused={paused||reduced||!inView||hidden} onFailure={()=>setFailed(true)}/></div>}<div className="engine-top"><span><i/> THE CONNECTED SYSTEM</span><span>MOVE TO EXPLORE</span></div><div className="node-tag node-tag-a"><span/>APPLICATIONS</div><div className="node-tag node-tag-b"><span/>AUTOMATION</div><div className="node-tag node-tag-c"><span/>INTELLIGENCE</div><div className="engine-bottom"><span>{failed?'CONNECTED BY DESIGN':'IDEAS → SYSTEMS → POSSIBILITIES'}</span><button onClick={()=>setPaused(!paused)} aria-label={paused?'Play animation':'Pause animation'} aria-pressed={paused} disabled={reduced||failed} title={reduced?'Reduced motion enabled':undefined}>{paused||reduced?<Play size={13}/>:<Pause size={13}/>}<span>{reduced?'STILL MODE':paused?'PLAY':'PAUSE'}</span></button></div></div></div>
 <div className="hero-foot"><span>BASED IN CAGAYAN DE ORO, PHILIPPINES</span><span>ZOHO DEVELOPMENT <i/> AUTOMATION <i/> DIGITAL EXPERIENCES</span><a href="#work" aria-label="Scroll to selected work"><ArrowDown size={18}/></a></div>
 </section>
 <div className="experience-strip"><div className="wrap strip-inner"><span>BUILT THROUGH<br/><strong>REAL EXPERIENCE.</strong></span>{[['rg26.jpg','RG26 Technologies','SOLUTIONS & TECHNOLOGY'],['briteph.jpg','BritePH','DESIGN & AUTOMATION'],['msu-iit.jpg','MSU–IIT','INFORMATION TECHNOLOGY']].map(([logo,name,role])=><div key={name}><img src={asset(`logos/${logo}`)} width="44" height="44" alt=""/><span><strong>{name}</strong><small>{role}</small></span></div>)}</div></div>
 <section className="section wrap" id="work"><Mark number="01 / 04">SELECTED WORK</Mark><div className="section-head" data-reveal><h2>Zoho systems.<br/><span>Built for real work.</span></h2><p>A selection of applications, automations, and interfaces. Built around real people and the way they work.</p></div>
 <div className="featured-grid">{projects.slice(0,3).map((p,i)=><article className={`feature feature-${i}`} key={p.slug} data-reveal><a href={asset(`case-studies/${p.slug}.html`)} className="feature-visual" aria-label={`Read ${p.short} case study`}><div className="visual-header"><span>{String(i+1).padStart(2,'0')} / {p.label}</span><ArrowUpRight size={23}/></div><div className="project-screen"><img src={asset(p.image!)} alt={`${p.short} project screenshot`} loading="lazy" width="1024" height="641"/></div><div className="visual-footer"><span>{p.org}</span><span>EXPLORE PROJECT ↗</span></div></a><div className="feature-copy"><span className="eyebrow">{p.type}</span><h3><a href={asset(`case-studies/${p.slug}.html`)}>{p.name}</a></h3><p>{p.description}</p><a className="under-link project-read" href={asset(`case-studies/${p.slug}.html`)}>Read case study <ArrowUpRight size={16}/></a></div></article>)}</div>
 <details className="project-index"><summary><span>Explore 11 more projects</span><Plus className="expand-icon" size={22}/></summary><div className="index-heading"><div className="filter-controls" aria-label="Filter projects">{[['all','All work'],['zoho','Zoho'],['other','Beyond Zoho']].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} aria-pressed={filter===v}>{l}</button>)}</div></div><div className="archive-list" aria-live="polite">{projects.slice(3).filter(p=>filter==='all'||(filter==='zoho'?p.zoho:!p.zoho)).map(p=><a className="archive-row" href={asset(`case-studies/${p.slug}.html`)} key={p.slug}><span>{String(projects.indexOf(p)+1).padStart(2,'0')}</span><strong>{p.short}</strong><span>{p.type}</span><ArrowUpRight size={21}/></a>)}</div></details></section>
 <section className="capabilities"><div className="wrap"><Mark number="THE APPROACH">LESS FRICTION. MORE FORWARD.</Mark><div className="capabilities-head"><h2>From “what if”<br/>to <em>working.</em></h2><p>Good software starts with understanding the work. I connect the dots between business goals, thoughtful design, and practical delivery.</p></div><div className="capability-grid">{[{Icon:ScanLine,n:'01',title:'Understand the system',text:'Map the workflow, ask the right questions, and turn business requirements into a clear plan.',tags:'DISCOVERY / REQUIREMENTS'},{Icon:Workflow,n:'02',title:'Build the connections',text:'Bring applications, interfaces, and data together with Zoho, custom development, and automation.',tags:'ZOHO / APIS / DEVELOPMENT'},{Icon:Layers3,n:'03',title:'Make it work for people',text:'Design for everyday use. Test, document, and support the people who keep the system moving.',tags:'UI/UX / DELIVERY / SUPPORT'}].map(c=><article key={c.n} data-reveal><div><c.Icon size={29} strokeWidth={1.2}/><span>{c.n}</span></div><h3>{c.title}</h3><p>{c.text}</p><span className="eyebrow">{c.tags}</span></article>)}</div></div></section>
 <section className="section wrap about" id="about"><Mark number="02 / 04">THE PERSON BEHIND THE SYSTEMS</Mark><div className="about-layout"><div className="about-image" data-reveal><img src={asset('ian-about-portrait.png')} alt="Ian Van Anthony Gutierrez" width="1024" height="1536" loading="lazy"/><div className="photo-caption"><span>IAN GUTIERREZ</span><span>DEVELOPER. DESIGNER. CONNECTOR.</span></div></div><div className="about-copy" data-reveal><h2>A builder.<br/>A systems thinker.<br/><span>Your next collaborator.</span></h2><p>I’m Ian Van Anthony Gutierrez, a solutions developer and technology project manager based in the Philippines.</p><p>My work sits where business meets technology: Zoho development, AI integration, data analytics, UI/UX, and frontend development. I care about the details—and how everything fits together.</p><p>At RG26 Technologies and BritePH, I’ve worked with stakeholders and technical teams to build custom systems and support the people who use them.</p><a className="under-link" href={linkedIn} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <ArrowUpRight size={18}/></a></div></div>
 <div className="experience-list"><h3>Where I’ve built.</h3>{[
 {dates:'JUL 2023 — JUN 2026',company:'RG26 Technologies',role:'Solutions Developer · Technology & Project Management',logo:'rg26.jpg',points:['Developed and managed Zoho Creator applications and integrated Zoho One systems.','Built an AI application with Zoho Creator and OpenAI; contributed to the company achieving Zoho Partner status.','Delivered application features, analytics dashboards, Figma interfaces, and Google Workspace tools.','Managed requirements, user access, onboarding, documentation, and operational IT support.']},
 {dates:'JUN 2022 — JUN 2023',company:'BritePH Design and Automation',role:'Developer',logo:'briteph.jpg',points:['Designed interfaces in Figma and Adobe XD; built frontends with React, TypeScript, HTML, CSS, and Tailwind CSS.','Built and maintained websites using WordPress, System.io, Duda, and Zoho Sites.','Supported Zoho CRM, Campaigns, Analytics, Flow, Writer, and WorkDrive workflows.','Prepared reporting data, automated processes with Zapier, and created project documentation.']},
 {dates:'JAN — MAY 2022',company:'MSU–IIT OVCPD',role:'Data Analyst & DBA Intern',logo:'msu-iit.jpg',points:['Designed an entity relationship diagram for the university’s major final outputs website.','Developed an office website with Google Sites and KPI reports in Excel and Google Sheets.','Analyzed university outputs, prepared presentations, and supported project handover.']}
 ].map(e=><details key={e.company}><summary><span className="eyebrow">{e.dates}</span><span className="role-company"><img src={asset(`logos/${e.logo}`)} alt="" width="36" height="36"/><span><strong>{e.company}</strong><small>{e.role}</small></span></span><Plus className="expand-icon" size={22}/></summary><ul>{e.points.map(t=><li key={t}>{t}</li>)}</ul></details>)}</div>
 <details className="toolkit"><summary><span>Tools of the trade</span><Plus className="expand-icon"/></summary><div>{[['Zoho & automation','Zoho One · Creator · Deluge · CRM · Analytics · Campaigns · Flow · Desk · Projects · Zapier · OpenAI integrations'],['Development & data','React · JavaScript · TypeScript · HTML · CSS · Tailwind CSS · Java · Python · PHP · SQL · MySQL · MongoDB · GitHub'],['Design & delivery','Figma · Adobe XD · WordPress · Duda · Google Workspace · Microsoft 365 · Project management · Technical documentation']].map(([t,d])=><section key={t}><h4>{t}</h4><p>{d}</p></section>)}</div></details>
 </section>
 <section className="education-section" id="background"><div className="wrap education-layout"><div className="education-heading"><h2>A foundation<br/>to <em>build on.</em></h2><p>A foundation in information technology.<br/>An ongoing drive to build what comes next.</p></div><img className="education-portrait" src={asset('ian-education-portrait.png')} alt="Ian in MSU–IIT graduation attire" width="1086" height="1448" loading="lazy"/><div className="education-detail"><img src={asset('logos/msu-iit.jpg')} alt="MSU–IIT logo" width="50" height="50" loading="lazy"/><span className="eyebrow">2018 — 2022</span><h3>BS Information<br/>Technology</h3><p>Major in Databases<br/>Mindanao State University –<br/>Iligan Institute of Technology</p><span className="honor">CUM LAUDE <ArrowUpRight size={15}/></span><details><summary>More background <Plus size={15}/></summary><p>ROTC Cadet. Previously a Hazard Engineer Assistant at UKC Builders Inc during work immersion, March–June 2017.</p><p>English · Filipino · Bisaya<br/>Basic Japanese / Nihongo</p></details></div></div></section>
 <section className="section wrap recognition" id="recognition"><Mark number="03 / 04">RECOGNITION & CONTINUED LEARNING</Mark><div className="section-head"><h2>Recognized by<br/><span>Zoho Creator.</span></h2><p>Four recognitions from Zoho Creator Developers’ Month 2023, plus the learning behind the work.</p></div><div className="award-grid">{awards.map(([title,img],i)=><button className="award" key={title} onClick={e=>open({src:`credentials/${img}`,title,meta:'Zoho Creator · Developers’ Month 2023'},e)}><span className="award-top"><img src={asset('logos/zoho.jpg')} alt="Zoho" width="28" height="28"/><span>2023</span></span><span className="award-art"><img src={asset(`credentials/${img}`)} alt="" width="1430" height="885" loading="lazy"/></span><span className="award-title">{title}</span><span className="award-bottom">ZOHO CREATOR <ArrowUpRight size={17}/></span></button>)}</div><div className="certificates-heading"><h3>Certifications & course completions</h3></div><div className="certificates-grid">{credentials.map(c=><button className="certificate" key={c.title} onClick={e=>open({src:`credentials/${c.img}`,title:c.title,meta:c.meta},e)}><span className="certificate-image"><img src={asset(`credentials/${c.img}`)} alt={`${c.title} preview`} loading="lazy"/></span><span className="certificate-info"><img src={asset(`logos/${c.logo}`)} alt={c.logo==='skillup.png'?'SkillUp logo':c.logo==='csx-cybersecurity.png'?'CSX Cybersecurity Fundamentals logo':''} width="38" height="38"/><span><small>{c.meta}</small><strong>{c.title}</strong><small>{c.detail}</small></span><ArrowUpRight size={18}/></span></button>)}</div><button className="under-link internship-link" onClick={e=>open({src:'credentials/internship-completion-photo.jpg',title:'Internship completion photo',meta:'MSU–IIT · 2022'},e)}>View internship completion photo <ArrowUpRight size={17}/></button></section>
 <section className="contact" id="contact"><div className="wrap"><Mark number="04 / 04">YOUR NEXT CHAPTER</Mark><div className="contact-heading"><h2>Something complex<br/>on your mind?<br/><em>Let’s untangle it.</em></h2><a className="contact-orb" href={`mailto:${email}`} aria-label="Email Ian about a project"><ArrowUpRight strokeWidth={1} size={72}/></a></div><div className="contact-bottom"><div><p>Tell me what you’re building.<br/>Let’s find the right way forward.</p><a className="email" href={`mailto:${email}`}>{email}</a><button className="copy" onClick={copy} aria-label="Copy email address">{copied?<Check size={17}/>:<Copy size={17}/>}</button><span className="copy-status" role="status">{copied?'Email copied':copyError?'Copy unavailable. Please use the email link.':''}</span></div><div className="socials"><a href={linkedIn} target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={18}/></a><a href="tel:+639709584212">+63 970 958 4212 <ArrowUpRight size={18}/></a><span>Cagayan de Oro, Philippines</span></div></div></div></section>
 </main><footer className="footer wrap"><a className="brand" href="#top" aria-label="Back to top">ian<span>.</span></a><span>© {new Date().getFullYear()} IAN VAN ANTHONY GUTIERREZ</span><nav aria-label="Footer navigation"><a href={asset('terms.html')}>Terms</a><a href={asset('privacy.html')}>Privacy</a><a href={asset('admin.html')}>Admin</a><a href="#top">Back to top ↑</a></nav></footer>
 <dialog ref={dialog} aria-labelledby="preview-title" className={zoom?"preview-dialog zoomed":"preview-dialog"} onCancel={()=>setPreview(null)} onClick={e=>{if(e.target===e.currentTarget)setPreview(null)}}>{preview&&<div className="preview-content"><header><div><small>{preview.meta}</small><h2 id="preview-title">{preview.title}</h2></div><button aria-label={zoom?"Fit image":"Zoom image"} onClick={()=>setZoom(!zoom)}>{zoom?<ZoomOut/>:<ZoomIn/>}</button><button aria-label="Close image preview" onClick={()=>setPreview(null)}><X/></button></header><div className="preview-image-scroll"><img src={asset(preview.src)} alt={preview.title}/></div><a href={asset(preview.src)} target="_blank" rel="noopener noreferrer">Open full-size image <ArrowUpRight size={16}/></a></div>}</dialog>
 </>;
}
